# First Level

FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.* ./

RUN go mod download

COPY . .

RUN ["go", "build", "."]


# Second Level

FROM alpine

COPY --from=builder app/brief .
COPY --from=builder app/log.json .
COPY --from=builder app/mine.env .

CMD ["./brief"]