version: "3.8"

services:
  postgres-instance:
    image: postgres:latest
    restart: "on-failure"
    environment:
      POSTGRES_USER: default
      POSTGRES_DB: brief
      POSTGRES_PASSWORD: password
    container_name: postgres-brief
    ports:
      - '5433:5432'
    # volumes:
    #   - /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - "my_network"

networks:
  my_network: